version: '3.7'
services:
  mysql:
    image: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: bluebell
    container_name: Mysql-bluebell

  redis:
    image: redis
    ports:
      - "16379:6379"
    container_name: Redis-bluebell

  bluebell:
    build:
      context: .
      dockerfile: dockerfile
    command: sh -c "./wait-for.sh Mysql-bluebell:3306 Redis-bluebell:6379 -- ./bluebell"
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8888"
    container_name: App-bluebell

  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - bluebell
    container_name: Nginx-bluebell
