basePath: /api/v1
definitions:
  dto.CommunityDto:
    properties:
      community_id:
        type: string
      community_name:
        type: string
      createdAt:
        type: string
      introduction:
        type: string
    type: object
  dto.PostDto:
    properties:
      author_name:
        type: string
      community:
        $ref: '#/definitions/dto.CommunityDto'
      content:
        type: string
      createdAt:
        type: string
      post_id:
        type: string
      status:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      vote_num:
        type: string
    type: object
host: 127.0.0.1:8888
info:
  contact:
    name: chuxin
    url: github.com/chuxin0816
  description: bluebell API文档
  license:
    name: Apache 2.0
  title: bluebell API
  version: "1.0"
paths:
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        type: string
      - in: query
        name: community_id
        type: integer
      - in: query
        name: order
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.PostDto'
            type: array
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口(api分组展示使用的)
swagger: "2.0"
